name: Test project

on:
  issues:
    types: [opened]

jobs:
  good:
    runs-on: ubuntu-latest
    steps:
      - name: Good bye!
        run: echo "Goodbye"

  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo '${{ toJSON(github.event) }}' | jq

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.head_commit.id }}
          body: |
            This is a multi-line test comment  
            - With GitHub **Markdown** :sparkles:  
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
